services:
    service.infrastructure.access_token_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine',  getRepository]
        arguments:
            - Sidebeep\Service\Domain\Model\AccessToken

    service.infrastructure.auth_code_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine',  getRepository]
        arguments:
            - Sidebeep\Service\Domain\Model\AuthCode

    service.infrastructure.client_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine',  getRepository]
        arguments:
            - Sidebeep\Service\Domain\Model\Client

    service.infrastructure.refresh_token_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine',  getRepository]
        arguments:
            - Sidebeep\Service\Domain\Model\RefreshToken

    service.infrastructure.scope_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine',  getRepository]
        arguments:
            - Sidebeep\Service\Domain\Model\Scope

    service.infrastructure.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine',  getRepository]
        arguments:
            - Sidebeep\Service\Domain\Model\User
        calls:
            - [setUserAuthorization, ['@service.application.user_authorization']]