framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing_%kernel.environment%.yml"
        strict_requirements: %kernel.debug%
    profiler:
        enabled: %kernel.debug%
    templating: { engines: ['twig'] }

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: %monolog_action_level%
            handler: nested
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

jms_serializer:
    property_naming:
        separator:  _
        lower_case: true
    metadata:
        auto_detection: true
        directories:
            PresentationBundle:
                namespace_prefix: "Sidebeep\\Service"
                path: "@PresentationBundle/Resources/config/serializer"
fos_rest:
    view:
        view_response_listener: force
    format_listener:
        rules:
            - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: false }
    exception:
        enabled: true
        codes:
            'SidebeepService\RequestAdapter\InvalidAttributesException': 422
            'SidebeepService\Exception\Domain\DomainLevelInvalidAttributesException': 422
    allowed_methods_listener: true
    param_fetcher_listener: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    routing_loader:
        default_format: json
        include_format: false

old_sound_rabbit_mq:
    connections:
        default:
            host:     "%messaging_server_host%"
            port:     "%messaging_server_port%"
            user:     "%messaging_server_user%"
            password: "%messaging_server_password%"
            vhost:    '/'

    producers:
        billing:
            connection: default
            exchange_options: { name: 'billing', type: topic }
        email_transaction:
            connection: default
            exchange_options: { name: 'email_notification', type: topic }

doctrine_mongodb:
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: sidebeep_billing
    document_managers:
        default:
            mappings:
                InfrastructureBundle:
                    type: yml
                    dir: Persistance/Doctrine/config
                    prefix: Sidebeep\Service