authorize:
    path: /
    defaults:
        _controller: service.controller.authorize:indexAction
        _format: html
    methods: [GET, POST]

token:
    path: /token
    defaults: { _controller: service.controller.token:indexAction }
    methods: [POST]

verify:
    path: /verify
    defaults: { _controller: service.controller.resource_server:indexAction }
    methods: [GET]