Sidebeep\Service\UI\Response\SampleResponse:
    exclusion_policy: ALL
    read_only: false
    access_type: property

    properties:
        prop_1:
            expose: true
            access_type: property
            type: string
            serialized_name: prop_2
        prop_2:
            expose: true
            access_type: property
            type: string
            serialized_name: prop_1