services:
    service.controller.schedules:
        class: Sidebeep\Service\UI\Controller\SchedulesController
        arguments:
            - '@service.repo.query.query_schedules'
            - '@service.repo.query.query_schedules_data'
            - '@service.repo.command.schedules_data'
            - '@command_bus'
            - '@fos_rest.view_handler'